# Generated by Django 4.2 on 2023-12-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('for_shop_type', models.CharField(choices=[('sport', 'Sport'), ('food', 'Food'), ('electronics', 'Electronics')], max_length=20, verbose_name='Для типу магазину')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('type', models.CharField(choices=[('sport', 'Sport'), ('food', 'Food'), ('electronics', 'Electronics')], max_length=20, verbose_name='Тип')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Довгота')),
                ('sales_commission', models.SmallIntegerField(default=0, verbose_name='Комісія з продажів (відсоток)')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазини',
                'ordering': ['name'],
            },
        ),
    ]
