# Generated by Django 4.2 on 2023-12-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name'], 'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазини'},
        ),
    ]
